### ISSUE TITLE
Making pattern library

### ISSUE THREAD

**Issue by hongnguyen11** [hongnguyen11/ecommerce-pattern-library#2]
I’m having problem with the Making patterns assignment. I followed the instructions but when I checked it online the css style didn’t link to the button. I really don’t know why that happened and how to fix it. Please help meeee! Thanks

@thomasjbradley

**Comment by thomasjbradley** [comment]
The `main.css` file is missing some code.

At the top of the file, as the very first lines, here:
https://github.com/hongnguyen11/ecommerce-pattern-library/blob/master/css/main.css#L1-L2

There needs to be 2 lines of three dashes, like;

```
---
---
```

**Comment by hongnguyen11** [comment]
It works. Thank you so much.
