### ISSUE TITLE
Marks for "Building pages with patterns"

### ISSUE THREAD

**Issue by hongnguyen11** [hongnguyen11/ecommerce-pattern-library#3]
<img width="1413" alt="Screen Shot 2020-03-19 at 1 58 39 AM" src="https://user-images.githubusercontent.com/43138193/77099836-01ffe500-69eb-11ea-85e3-46646709e961.png">
<img width="1414" alt="Screen Shot 2020-03-19 at 1 58 48 AM" src="https://user-images.githubusercontent.com/43138193/77099853-075d2f80-69eb-11ea-9e87-8e735fcfac5a.png">

@thomasjbradley

**Comment by thomasjbradley** [comment]
💯
